### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by bhanuc** [ryankennedyio/ib-docker#1]
On running - docker-compose up, I get the following output.
Pulling tws (ryankennedyio/ib-docker:latest)...
Pulling repository docker.io/ryankennedyio/ib-docker
ERROR: Error: image ryankennedyio/ib-docker:latest not found

**Comment by ryankennedyio** [comment]
Hey @bhanuc, just make sure you build the image yourself using `docker build`.

I've purposely not provided an image because it's bad practice for people to use a public image for something like this. Technically, there's nothing stopping me installing a backdoor in my container (not the public source) and pushing it to dockerhub, so I could get your IB credentials. So, to promote best practice, you've got to build it yourself :)

**Comment by bhanuc** [comment]
Thanks for the edit and quick reply.
