### ISSUE TITLE
ERROR: repository ryankennedyio/ib-docker not found: does not exist or no pull access

### ISSUE THREAD

**Issue by chrism2671** [ryankennedyio/ib-docker#7]
I'm getting the following error when trying to start the container. I'm not a docker expert so I might be missing something (is that repository supposed to be on dockerhub?). I'd appreciate if you have any insight!
Thanks!
Chris.

```
$ docker-compose up
Pulling tws (ryankennedyio/ib-docker:latest)...
ERROR: repository ryankennedyio/ib-docker not found: does not exist or no pull access

```

**Comment by ryankennedyio** [comment]
Hey @chrism2671 ,

You'll need to build the container yourself -- you likely don't want to trust a container you pull from a public repository with your brokerage account keys :) I didn't upload to dockerhub because I don't want to promote bad security practice with these things.

From within the repo, something like:
`docker build -t chrism/ib-tocker .` should start the build process.

**Comment by chrism2671** [comment]
OK, I managed to get it to run, not with the command in the instructions (which seems to force using dockerhub), but with `docker run -it --rm my_image`.

I have the following error come up:
/opt/IBController/Scripts/DisplayBannerAndLaunch.sh: line 4: /version: No such file or directory

After a little digging, it seems that ${IBC_PATH} isn't set. Where should it be set?

**Comment by ryankennedyio** [comment]
Hmm. I've just reinstalled everything from scratch according to the quick steps as described in the README.md 

Since you're starting the image with `docker run`, you might not be loading all the environment variables correctly. Notice in the `docker-compose.yml` file there are roughly a dozen environment variables -- I think you definitely need to be starting the image with `docker-compose up -d` from within the repository to load these correctly.


Are you able to start again from step 1 and let me know which of the commands fails?

**Comment by chrism2671** [comment]
I figured it out.

Where instruction 2 says `docker build -t <pick-a-name> .`

I think we should an instruction that in `docker-compose.yml` you need to also set the `tws:image:` field to be `<pick-a-name>`. I'm not sure if this step is obvious, but I've never used docker before.

**Comment by ryankennedyio** [comment]
Glad to hear @chrism2671 ! Yes I think that was slightly assumed knowledge, maybe incorrectly on my part. Will update the readme in a second with a helpful link.

**Comment by chrism2671** [comment]
Thanks! One further question. I did get the instance to start, and IB to login successfully. The instance seems to expose the ports 4003/5900 correctly (checked with nmap and telnet), but disconnects anything that connects to it immediately. I'm certain this is an issue related to my setup, but any ideas what it might be?

By the way, well done with this, this is so much better than running gateway manually!
